### ISSUE TITLE
Add notes about Linux udev rules

### ISSUE THREAD

**Issue by didim99** [baryluk/fnirsi-usb-power-data-logger#1]
Hello! I'm developing a same [tool](https://github.com/didim99/witrn-ui) for WITRN meters and know way to run `pyusb` without root access on Linux. All what you need is add [rules file](https://github.com/didim99/witrn-ui/blob/master/udev/90-usbmeter.rules) in `/etc/udev/rules.d` and update udev as described [here](https://unix.stackexchange.com/questions/39370/how-to-reload-udev-rules-without-reboot) (or reboot). I was tested your script with FNB48 and all works fine. Nice work, thank you!

**Comment by baryluk** [comment]
Hi @didim99 . Yes, I am aware of rules file for udev. Still to install them and restart udev you need root :) 

Glad you found a way to make it work.

Cheers.

**Comment by baryluk** [comment]
@didim99 I will copy your udev rules to this repo, and add info to the README if that is ok?

**Comment by didim99** [comment]
@baryluk of course, you can copy it.
