### ISSUE TITLE
Access to the internal storage of FNB58 

### ISSUE THREAD

**Issue by yildirayk** [baryluk/fnirsi-usb-power-data-logger#6]
FNB58 has internal storage which makes it possible to do offline recording. I am not sure if FNB48 has also. 

So how can we export internal storage data ? @baryluk @didim99

**Comment by baryluk** [comment]
My FNB48 does not have such feature.

I expect it is some simple FAT32 / FAT16 file system with simple file structure. Probably simple binary format or CSV.

I will be ordering FNB58 soon, but I personally do not require offline recording, as I usually feed data to live monitoring / recording systems in real time. So offline recording is not an option.

I guess, offline recording does reduce cable clutter, ensures galvanic isolation of systems (no potential ground loops either), and allow you to record things far from computer (i.e. in backpack, in the field, etc).

Not sure if this repo is suitable for tools for parsing the file from FNB58. Probably a small utility in separate repo is way to go.

If you can upload a sample file in this ticket, we could take a look.

**Comment by baryluk** [comment]
You can try detecting storage first using `lsblk`

**Comment by yildirayk** [comment]
`sda           8:0    1    12M  0 disk /media/yildiray/387D-7906`

I could see the disk a moment ago, I could list the files in that directory. There were two files, both were not human readable. A .dat file for settings and another file I don't remember now. But there was not a data file like .csv. Then I reboot to Windows to see if they are visible there and ran the Windows software. Unfortunately, the Windows software crushes when I connect the device. I use Windows 11. Now I am back to Ubuntu and but this time I cannot see the files in Fnirsi directory. Maybe @didim99 can comment.

**Comment by didim99** [comment]
> My FNB48 does not have such feature.

@baryluk actually, FNB48 has no emulated internal USB MS device, however, offline recording is supported here (using onboard separate memory chip), and you can export this records by Windows software in proprietary binary format. See my [USB-meters comparison table](https://docs.google.com/spreadsheets/d/1J6IUJzHqSXUyQrJMm-u4sP93dAfwVY6MfWwWz6Sufvo/edit#gid=0) for more details (it's written in russian, but you can use Google Translate to reed).

> Not sure if this repo is suitable for tools for parsing the file from FNB58. Probably a small utility in separate repo is way to go.

@baryluk yes, separate utility is right way. Already I'm working on it (processing files from FNIRSI software, that was requested from russian users community on 4PDA forum). Probably it also will be suitable for reading offline records from FNB58. I will add this parser to my [usbmeter-utils](https://github.com/didim99/usbmeter-utils) repo. @yildirayk at the moment I can't say anything about FNB58 internal storage, but work in progress, stay tuned.

**Comment by baryluk** [comment]
@didim99 Yes, I am aware of offline FNB48 storage, I didn't know it can be transfered to computer using Windows software. Interesting. I always tough it can be only stored and read back on the usb meter itself, not transferred to PC.

I ordered my FNB58. Will have it in few weeks.

**Comment by didim99** [comment]
@yildirayk finally, I wrote CFN to CSV converter in my repo mentioned above (sorry @baryluk, I continuing this conversation in your issue because topic started here).

I tested it on set of files recorded from FNB48 and FNB58 USB-meters via FNIRSI toolbox v0.0.6 and all works fine. Also I tested offline record import from FNB48 and this works too.

Unfortunately, I can't test offline record import from my FNB58 (fw v0.66) because FNIRSI software shows very strange curves (hundreds of volts and amps instead of real data shown on tester screen). Also I don't see anything in the virtual Mass Storage device provided by FNB58 after finishing offline record and don't know how to produce files there. If you have some samples from FNB58 offline storage, please, share them of explain how to get it.

**Comment by didim99** [comment]
@baryluk I think you can close this issue because it is not relevant for this repo and actually fixed in my one.
