### ISSUE TITLE
gnuplot not responding for --live option

### ISSUE THREAD

**Issue by zdun8** [baryluk/fnirsi-usb-power-data-logger#8]
Hello, 

I observe that for --live option, gnuplot is not responding and system asks to kill it. 
OS: Ubuntu 20.04
gnuplot version: 5.2 patchlevel 8
FNB58: 0.67 firmware

Best regards,
Piotr Zdunek

**Comment by baryluk** [comment]
Hi.

Could show exactly how you start the logger script, and how you start the gnuplot?

**Comment by krisstakos** [comment]
Same issue for me on FNIRSI48P, OS:Pop_os
Without the --live argument I can see generated images but live graphs is not working.
I'm running as documented here in the repo:
`./plot.gnuplot /tmp/fnirsi-live.txt --live`
where in a separate terminal the logger is running

**Comment by krisstakos** [comment]
nvm, setting the terminal type to x11 fixed the issue
